services:
  backend:
    build: .
    container_name: recetas_backend
    restart: always
    ports:
      - "8000:8000"
    networks:
      - universal_db
    env_file:
      - .env
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /app
networks:
  universal_db:
    name: universal_db
    external: true
